### ISSUE TITLE
[frontend] [question-service] viewing/editing a question does not reset the question form

### ISSUE THREAD

**Issue by LeirdaKJW** [CS3219-AY2324S1/ay2324s1-course-assessment-g15#17]
As the title suggests, any action that views the question causes the next "add" to reference it instead of an empty form.
![image](https://github.com/CS3219-AY2324S1/ay2324s1-course-assessment-g15/assets/97372979/135250aa-eec1-475c-b9a5-414637ac61e9)

**Comment by dsja612** [comment]
closed by #14
